services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - oss
  mongo:
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=MONGODB_ROOT_PASSWORD
      - MONGODB_USERNAME=MONGODB_USERNAME
      - MONGODB_PASSWORD=MONGODB_PASSWORD
    volumes:
      - mongodb_data:/bitnami/mongodb
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend
  oss:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
volumes:
  mongodb_data:
  minio_data:


